### ISSUE TITLE
Not an issue, just a query

### ISSUE THREAD

**Issue by hDmtP** [MTrajK/coding-problems#11]
https://github.com/MTrajK/coding-problems/blob/62b8da6bb99a564bec33b7864a61122b7bab8df0/Math/check_if_point_inside_polygon.py#L32

why prev = curr ?

**Comment by MTrajK** [comment]
Hi, first of all, "prev" is short from "previous" and "curr" is short from "current" (previous and current points).
You could see that "prev" and "curr" are used 2 lines above `intersect(prev, curr, p)`, so for this method, we need to store the point from the **CURRENT** iteration so we could use it in the **NEXT** iteration.
