### ISSUE TITLE
coding-problems/Arrays/find_el_where_k_greater_or_equal.py /

### ISSUE THREAD

**Issue by Cfoxyer** [MTrajK/coding-problems#16]
in 30 line , why retuen 1 ?    list arr maybe have 1 . i don't undersdant.

**Comment by MTrajK** [comment]
_Copy-paste from the response on the comment:_

From the task "You have to find some number X greater than 0" so the first greater integer than 0 is 1. 
1 is the smallest possible integer (we're expecting all of the input numbers to be greater than 0).
We don't need logic to find the number that will be smaller or equal to all of the input numbers, it'll be always 1.
