### ISSUE TITLE
Link for, (Classpert - Data Structures and Algorithms Courses) is broken, plz fix it 

### ISSUE THREAD

**Issue by ghagevaibhav** [MTrajK/coding-problems#25]
It show's an error with the message of  "Sorry! We couldn't find any results for "data-structures-and-algorithms""

**Comment by MTrajK** [comment]
Thank you, something is wrong with the page. Just in case I'll wait several days for the page to be fixed, if nothing is changed I'll remove this link.

**Comment by MTrajK** [comment]
@wyugue added this link and as I could see he is a contributor on this platform (he's maintaining classpert/latinizer). I'll wait several days for him to investigate this.

**Comment by ghagevaibhav** [comment]
Yeah, thank you for responding quick. Happy Coding.

**Comment by MTrajK** [comment]
@vaibhav4516 and @wyugue deleted the link, more than 10 days passed.

**Comment by ghagevaibhav** [comment]
Thanks, appreciate your cooperation.
