### ISSUE TITLE
typing error in comment

### ISSUE THREAD

**Issue by ghost** [MTrajK/coding-problems#3]
Hi, Thank you for share useful codings to do research, I found a typing error in coding-problems/Arrays/jump_game.py.
Line 12 : If the current position is smaller **thant** the farthest position, then the end isn't reachable.

**Comment by dcjamespark** [comment]
> Hi, Thank you for share useful codings to do research, I found a typing error in coding-problems/Arrays/jump_game.py.
> Line 12 : If the current position is smaller **thant** the farthest position, then the end isn't reachable.

af

**Comment by ghost** [comment]
Hi, Thank you for share useful codings to do research, I found a typing error in coding-problems/Arrays/jump_game.py.
Line 12 : If the current position is smaller thant the farthest position, then the end isn't reachable.

**Comment by MTrajK** [comment]
Hi, you're welcome. Nice finding, thank you very much. I'll fix it right now.
