### ISSUE TITLE
I would like to work on length of Longest SubString without repeating Character. 

### ISSUE THREAD

**Issue by Shiv1202** [MTrajK/coding-problems#4]
Example 1:
Input: "abcabcbb"   Output: 3 
Explanation: The answer is "abc", with
the length of 3. 
Example 2:
Input: "bbbbb"      Output: 1
Explanation: The answer is "b", with the
length of 1

**Comment by MTrajK** [comment]
Hey, I think I don't understand the issue/question. Could you please give me more info? Or you need an explanation about the examples?

**Comment by Shiv1202** [comment]
I want to contribute a code about " length of longest SubString without repeating character.
In the above comment, I share an example of code.

**Comment by MTrajK** [comment]
There already exists a solution for that problem [Hashing DS/longest_substring_without_repeating_characters.py](https://github.com/MTrajK/coding-problems/blob/master/Hashing%20DS/longest_substring_without_repeating_characters.py)
I'm still not sure, you have a new solution?
If yes then make a pull request and I'll review it and merge it.

**Comment by arunkumarbs97** [comment]
#include <iostream.h> 
using namespace std;
int longestSubseq(char* myString) 
{ 
    int n = strlen(myString); 
    int currentLength = 1; // length of current running substring 
    int maxLength = 1;  
    int previousIndex;  
    int * alreadyVisited = new int[sizeof(int) * CharacterCount]; 
for (int i = 0; i < CharacterCount; i++) 
        alreadyVisited[i] = -1; 
alreadyVisited[myString[0]] = 0; 
  for (int i = 1; i < n; i++) { 
 previousIndex = alreadyVisited[myString[i]];  if (previousIndex == -1 || i - currentLength > previousIndex) 
            currentLength++; 
  else { 
        if (currentLength > maxLength) 
                maxLength = currentLength; 
currentLength = i - previousIndex; 
        } 
        alreadyVisited[myString[i]] = i; 
    } 
  
       if (currentLength > maxLength) 
        maxLength = currentLength; 
  
    free(alreadyVisited); 
    return maxLength; 
} 

int main() 
{ 
    char myString[] = "ABCBCA"; 
    cout << "My string is : " << myString << endl; 
    int len = longestSubseq(myString); 
    cout << "The length of the longest substring "
         << "with non repeating characters is : "
         << len; 
    
    return 0;
} 
// OUTPUT
// My string is : ABCBCB
The length of the longest substring with non repeating characters is : 3
